go.mod, modules/runes/repository/postgres/tx.go
Please provide a clear and concise description of the changes you've made and the problem they address. Include the purpose of the change, any relevant issues it solves, and the benefits it brings to the project. If this change introduces new features or adjustments, highlight them here.
=> fix: invalid pgx version

cmd/cmd_run.go, config.example.yaml, internal/config/config.go, pkg/middleware/requestcontext/PROXY-IP.md, pkg/middleware/requestcontext/errors.go, pkg/middleware/requestcontext/requestcontext.go, pkg/middleware/requestcontext/with_clientip.go, pkg/middleware/requestcontext/with_requestid.go, pkg/middleware/requestlogger/requestlogger.go
- `requestcontext` middleware is used to extract request information such as real client ip and request id, then add this information to context
- `requestlogger` middleware is used to logging request information for debugging and monitoring
=> feat(api): add request context and logger middleware

cmd/cmd_run.go, config.example.yaml, internal/config/config.go
move `requestip` middleware config to http config
=> refactor: move requestip config to http config

modules/runes/api/httphandler/get_transactions.go, modules/runes/database/postgresql/queries/data.sql, modules/runes/datagateway/runes.go, modules/runes/repository/postgres/gen/data.sql.go, modules/runes/repository/postgres/runes.go, modules/runes/usecase/get_transactions.go
Use block range to filtering transactions in Transactions API
=> feat(runes): get txs by block range

modules/runes/processor_process.go
=> feat: release v0.2.5

core/datasources/bitcoin_node.go, modules/runes/processor_process.go, pkg/btcclient/contract.go
Remove unused verbose query to reduce time needed to process etching transactions
=> feat: remove unnecessary verbose query

core/datasources/bitcoin_node.go, modules/runes/processor_process.go, pkg/btcclient/contract.go
=> feat: release v0.2.7

pkg/middleware/requestlogger/requestlogger.go
- `with` - adding kv fields from configurations to logger
- `withRequestHeaders` - adding specific req headers to logger
- structuring request queries logging format
=> feat: Request Logger fields

modules/runes/api/httphandler/get_holders.go, modules/runes/api/httphandler/get_token_info.go
Return "rune not found" error in api if rune id is not found instead of "Internal Server Error"
=> fix: return runes not found error if rune id in request is not found

modules/nodesale/api/httphandler/nodes.go, modules/nodesale/database/postgresql/queries/nodes.sql, modules/nodesale/datagateway/mocks/NodeSaleDataGatewayWithTx.go, modules/nodesale/datagateway/nodesale.go, modules/nodesale/repository/postgres/gen/nodes.sql.go, modules/nodesale/repository/postgres/repository.go
Modify Nodesale API to allow query all nodes from a deployment.
=> Modify Nodesale API to allow query all nodes from a deployment.

cmd/cmd_version.go, common/network.go, modules/runes/api/httphandler/get_current_block.go, modules/runes/api/httphandler/httphandler.go, modules/runes/constants/constants.go, modules/runes/event_hash.go, modules/runes/processor.go, modules/runes/processor_process.go, modules/runes/runes/rune.go
Add constant `common.NetworkFractalMainnet` and `common.NetworkFractalTestnet` and their chain configs.
=> feat: add fractal network constant

README.md, docs/README_tr.md
This pull request adds a Turkish translation of the README.md file. The following changes have been made:
Created a new file README.tr.md with the Turkish translation of the content in README.md.
Updated README.md to include a link to the Turkish version at the top of the file.
Providing documentation in turkish language can help non-English speaking contributors and users better understand and engage with the project.
How Has This Been Tested?
• Proofread the Turkish translation for accuracy and completeness.
• Verified that the link to README.tr.md in README.md works correctly.
=> Turkish translation

modules/runes/api/httphandler/get_holders.go
=> Release v0.4.1

common/bitcoin.go, common/network.go, modules/runes/constants/constants.go, modules/runes/processor.go, modules/runes/runes/flag.go, modules/runes/runes/rune.go, modules/runes/runes/rune_test.go, modules/runes/runes/tag.go
Add Fractal changes for Runes
1. Move halving interval constant to be under common.Network instead (210,000 for Bitcoin, 2,100,000 for Fractal)
2. Add starting headers for Runes Fractal
3. Add genesis rune for Runes Fractal
=> feat: add fractal support for runes

common/bitcoin.go, common/network.go, modules/runes/constants/constants.go, modules/runes/processor.go, modules/runes/runes/flag.go, modules/runes/runes/rune.go, modules/runes/runes/rune_test.go, modules/runes/runes/tag.go
=> Release v0.4.2

modules/runes/constants/constants.go, modules/runes/processor.go
=> Release v0.4.3

core/indexer/indexer.go, modules/runes/constants/constants.go, modules/runes/processor_process.go
=> Release 0.4.4

modules/runes/constants/constants.go, modules/runes/repository/postgres/mapper.go
=> fix: correctly insert etchedAt in rune entry

modules/runes/constants/constants.go, modules/runes/database/postgresql/migrations/000001_initialize_tables.up.sql, modules/runes/repository/postgres/mapper.go
=> Release v0.4.7

modules/runes/api/httphandler/get_transaction_by_hash.go, modules/runes/api/httphandler/get_transactions.go, modules/runes/api/httphandler/routes.go, modules/runes/repository/postgres/runes.go, modules/runes/usecase/get_transactions.go
=> Release v0.5.0

modules/runes/database/postgresql/queries/data.sql, modules/runes/repository/postgres/gen/data.sql.go
Change Get Tokens endpoint, `ongoing` scope, to sort by mint tx count
=> fix: order get ongoing tokens by mint transactions

modules/runes/runes.go
- only call VerifyStates if not api only
=> fix: only call VerifyStates if not api only

modules/runes/runes.go
=> Release v0.5.6

modules/runes/api/httphandler/get_token_info.go
Please provide a clear and concise description of the changes you've made and the problem they address. Include the purpose of the change, any relevant issues it solves, and the benefits it brings to the project. If this change introduces new features or adjustments, highlight them here.
=> feat: add etching tx hash for runes info api
